name: Run Tests Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Roda todo dia às 12h UTC (9h BRT)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    #- name: Install dependencies
    #  run: pip install -r requirements.txt
    #- name: Install latest compatible dependencies (ignora travas)
    #  run: |
    #    pip install --upgrade --no-deps $(awk '{print $1}' requirements.txt)

    - name: Instalar dependências (últimas versões)
      run: |
        pip install --upgrade pip
        pip install --upgrade $(sed 's/[<=>].*//' requirements.txt)

    - name: Run tests
      run: |
        pytest teste_compras.py > result.log || echo "Testes falharam"

    - name: Check if all tests passed
      id: check
      run: |
        if grep -q "Preço não encontrado visualmente" result.log; then
          echo "success=false" >> $GITHUB_OUTPUT
        else
          echo "success=true" >> $GITHUB_OUTPUT
        fi
    - name: Create email body
      id: email_content
      run: |
        echo "body<<EOF" >> $GITHUB_OUTPUT
        jq -r . resultado_cartas.json >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        echo "body<<EOF" >> $GITHUB_OUTPUT
        echo "✅ Cartas encontradas:" >> $GITHUB_OUTPUT
        jq -r '.encontradas[] | "- \(.0): R$ \(.1)"' resultado_cartas.json >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "❌ Cartas não encontradas:" >> $GITHUB_OUTPUT
        jq -r '.nao_encontradas[] | "- \(.)"' resultado_cartas.json >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Send success email
      if: steps.check.outputs.success == 'true'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "✅ Todas as cartas estão disponíveis!"
        to: marcelobs.victor@gmail.com
        from: ${{ secrets.EMAIL_USERNAME }}
        body: ${{ steps.email_content.outputs.body }}

    - name: Send failure email
      if: steps.check.outputs.success == 'false'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "❌ Carta(s) não encontradas"
        to: marcelobs.victo@gmail.com
        from: ${{ secrets.EMAIL_USERNAME }}
        body: ${{ steps.email_content.outputs.body }}
